config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :job_applications, only: [:index]
  end

  resources :job_applications, only: [:index]

  resources :job_offers do
    resources :job_applications, only: [:new, :create, :index]
  end

  resources :notifications, only: [:index]

  root "job_offers#index"
end

app/models/job_application.rb
# app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job_offer
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  def create
    @job_offer = JobOffer.find(params[:job_offer_id])
    @job_application = @job_offer.job_applications.build(user: current_user)

    if @job_application.save
      redirect_to user_job_applications_path(current_user), notice: "Has realizado la postulación exitosamente."
    else
      render :new
    end
  end
  
  def index
    if current_user.admin?
      @job_applications = JobApplication.all
    else
      @job_applications = current_user.job_applications
    end
  end


  def new
    @job_offer = JobOffer.find(params[:job_offer_id])
    @job_application = @job_offer.job_applications.build
  end
  
  
  
  def show
    @job_applications = JobApplication.where(job_offer_id: params[:id])
  end
  

  private

  def create_notification(job_offer)
    message = "Nueva solicitud de empleo: #{job_offer.title}"
    Notification.create(user: job_offer.user, message: message)
  end



  

  def job_application_params
    params.require(:job_application).permit(:job_offer_id)
  end
  
end

app/views/job_applications/index.html.erb
<div class="container">
  <h1>Postulaciones</h1>

  <% @job_applications.each do |job_application| %>
    <div class="card mb-3">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <h5 class="card-title">Oferta Laboral: <%= job_application.job_offer.title %></h5>
            <p class="card-text"><strong>Fecha de Postulación:</strong> <%= job_application.created_at %></p>
            <p class="card-text"><strong>Correo:</strong> <%= job_application.user.email %></p>
          </div>
          <div class="col-md-4">
            <% candidate = job_application.user %>
            <% if candidate.photo.attached? %>
              <%= image_tag candidate.photo.variant(resize_to_fill: [100, 100]), class: "rounded-circle", alt: "Avatar" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <p><%= link_to "Volver", user_job_applications_path(current_user), class: "btn btn-primary" %></p>
</div>

app/views/job_applications/new.html.erb
<div class="container">
  <div class="text-center">
    <h1>Postular a Oferta Laboral</h1>

    <%= form_with(model: @job_application, url: job_offer_job_applications_path(@job_offer), class: "form") do |form| %>
      <%= form.hidden_field :job_offer_id %>
      <%= form.submit "Postular", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/job_applications/show.html.erb
<div class="container">
  <h1>Mis Postulaciones</h1>

  <% current_user.job_applications.each do |job_application| %>
    <div class="card mb-3">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8">
            <h5 class="card-title">Oferta Laboral: <%= job_application.job_offer.title %></h5>
            <p class="card-text"><strong>Fecha de Postulación:</strong> <%= job_application.created_at %></p>
            <p class="card-text"><strong>Carta de Presentación:</strong></p>
            <p class="card-text"><%= job_application.cover_letter %></p>
          </div>
          <div class="col-md-4">
            <% candidate = job_application.user %>
            <% if candidate.photo.attached? %>
              <%= image_tag candidate.photo.variant(resize: "100x100"), class: "rounded-circle", alt: "Avatar" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <p><%= link_to "Volver", user_job_applications_path(current_user), class: "btn btn-primary" %></p>
</div>