config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :job_applications, only: [:index]
  end

  resources :job_applications, only: [:index]

  resources :job_offers do
    resources :job_applications, only: [:new, :create, :index]
  end

  resources :notifications, only: [:index]

  root "job_offers#index"
end

app/models/job_offer.rb
# app/models/job_offer.rb
class JobOffer < ApplicationRecord
  belongs_to :user
  has_many :job_applications
end

app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  
  def index
    @job_offers = JobOffer.includes(:user).all
    @job_offer = JobOffer.new # o cualquier lógica adicional necesaria para definir @job_offer
  end
  

  def show
    @job_offer = JobOffer.find(params[:id])
    @job_applications = @job_offer.job_applications
  end

  def new
    @job_offer = JobOffer.new
  end

  def create
    @job_offer = JobOffer.new(job_offer_params.merge(user: current_user))
  
    if @job_offer.save
      redirect_to @job_offer, notice: "Oferta laboral creada exitosamente."
    else
      render :new
    end
  end

  private

  def job_offer_params
    params.require(:job_offer).permit(:title, :description)
  end
end

app/views/job_offers/_form.html.erb
<%= form_with(model: job_offer, url: job_offers_path, class: "form") do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/job_offers/index.html.erb
<div class="container">
  <div class="text-center">
    <% @job_offers.each do |job_offer| %>
      <div class="card mb-3">
        <div class="card-body">
          <% user = job_offer.user %>
          <% if user.photo.attached? %>
            <%= image_tag url_for(user.photo) %>
          <% end %>
          <h5 class="card-title"><%= job_offer.title %></h5>
          <p class="card-text"><%= job_offer.description %></p>
          
          <% if current_user && !current_user.admin? %>
            <%= link_to 'Postular', new_job_offer_job_application_path(job_offer), class: "btn btn-primary" %>
          <% end %>
          <%= link_to 'Ver', job_offer, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/job_offers/new.html.erb
<h1>Nueva Oferta Laboral</h1>

<%= form_with(model: @job_offer, url: job_offers_path, class: "form") do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Crear Oferta Laboral", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

<%= link_to 'Volver', job_offers_path, class: "btn btn-secondary mt-3" %>

app/views/job_offers/show.html.erb
<h1><%= @job_offer.title %></h1>
<p><%= @job_offer.description %></p>
<p>Empresa: <%= @job_offer.user.email %></p>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
    <%= value %>
  </div>
<% end %>

<%= link_to 'Volver', job_offers_path, class: "btn btn-primary" %>