config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    resources :job_applications, only: [:index]
  end

  resources :job_applications, only: [:index]

  resources :job_offers do
    resources :job_applications, only: [:new, :create, :index]
  end

  resources :notifications, only: [:index]

  root "job_offers#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">IntraJobs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#">Logged in as: <%= current_user.email %></a>
          </li>
          <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_job_offer_path %>">Crear</a>
            </li>
            <li class="nav-item">
            <%= link_to "Todas las Postulaciones", job_applications_path, class: "nav-link" %>
          </li>
          <% else %>
          <%= link_to "Mis Postulaciones", user_job_applications_path(current_user), class: "nav-link" %>
          
          <% end %>
          <li class="nav-item">
            <a class="nav-link" rel="nofollow" data-method="delete" href="<%= destroy_user_session_path %>">Logout</a>
          </li>
        <% else %>
          
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntraJobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">User: admin@admin.com</h5>
                <p class="card-text">Pass: 123456</p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">User: user@user.com</h5>
                <p class="card-text">Pass: 123456</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>